from spells import Spell

SPELL_LIST = {
    "blindness": {
        "dmg": 0,
        "mana_cost": 30,
        "effects": {"blind": 1},
        "delivery": "projectile",
        "projectile_img": "assets/projectiles/blindness.png",
    },
    "blitz": {
        "dmg": 0,
        "mana_cost": 10,
        "effects": {"blitz": 1},
        "delivery": "instant",
    },
    "counterspell": {
        "dmg": 0,
        "mana_cost": 50,
        "effects": {"counter": 1},
        "delivery": "instant",
    },
    "curse": {
        "dmg": 0,
        "mana_cost": 40,
        "effects": {"curse": 1},
        "delivery": "projectile",
        "projectile_img": "assets/projectiles/curse.png",
    },
    "fireball": {
        "dmg": 50,
        "mana_cost": 30,
        "effects": {"burning": .1},
        "delivery": "projectile",
        "projectile_img": "assets/projectiles/fireball.png",
    },
    "frostbite": {
        "dmg": 25,
        "mana_cost": 20,
        "effects": {"freezing": .1},
        "delivery": "projectile",
        "projectile_img": "assets/projectiles/frostbite.png",
    },
    "glaciate": {
        "dmg": 0,
        "mana_cost": 30,
        "effects": {"glaciate": 1},
        "bonus_chance": .25,
        "delivery": "instant",
    },
    "kindling": {
        "dmg": 0,
        "mana_cost": 30,
        "effects": {"kindling": 1},
        "bonus_chance": .25,
        "delivery": "instant",
    },
    "leech": {
        "dmg": 20,
        "mana_cost": 40,
        "effects": {"leech": 1},
        "delivery": "projectile",
        "projectile_img": "assets/projectiles/leech.png",
        "leech": True,
    },
    "roulette": {
        "dmg": 0,
        "mana_cost": 80,
        "effects": {"blind": .5, "burning": .5, "curse": .5, "freezing": .5, "glaciate": .5, "kindling": .5, "leech": .5, "shield": .5},
        "delivery": "instant",
    },
    "shield": {
        "dmg": 0,
        "mana_cost": 50,
        "effects": {"shield": 1},
        "delivery": "instant",
    },
    "spike": {
        "dmg": 20,
        "mana_cost": 10,
        "effects": {},
        "delivery": "projectile",
        "projectile_img": "assets/projectiles/spike.png",
    },
}
